name: 'Setup Docker CI Environment'
description: 'Creates the LunaSec CI build environment'

inputs:
  merge_master:
    description: 'If true, this merges the master branch during setup.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker BuildKit
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true # sets buildx as the default for docker, which should apply to docker-compose commands
        driver: docker

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    # specifically tag this bootstrap container to prevent rebuilds
    - name: Build Lerna Bootstrap container
      shell: bash
      env:
        # avoid warnings like "tput: No value for $TERM and no -T specified"
        TERM: xterm
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
      run: docker build --progress plain -f ./js/docker/demo.dockerfile -t lerna-bootstrap --target lerna-bootstrap .

    - name: Build CLI Container
      shell: bash
      env:
        # avoid warnings like "tput: No value for $TERM and no -T specified"
        TERM: xterm
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
      run: docker build --progress plain -f ./js/docker/demo.dockerfile -t repo_lunasec-cli --target lunasec-cli .
